name: Build Image
on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@1.0.2
        with:
          publish: true
          imageName: superng6/aria2
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: latest
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
